name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: darwinwin.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      timeout-minutes: 1

    - name: Create Solution Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake/premake5.exe vs2022
      timeout-minutes: 1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /v:m
      timeout-minutes: 5
    
    - uses: actions/upload-artifact@v3
      with:
        name: build-win64
        path: darwinwin/builds/bin/darwinwin.exe
        timeout-minutes: 1

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-win64
        timeout-minutes: 1

    - name: Run Tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./darwinwin --test-only
      timeout-minutes: 1